#! /bin/sh
set -e

LISP_PKG=puri

case "$1" in
    configure)
	register-common-lisp-source ${LISP_PKG}
	;;
    abort-upgrade|abort-remove|abort-deconfigure)
	;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
	;;
esac

#DEBHELPER#

exit 0


